title: "PortusSophia™ Public Orientation"
description: "High-level architecture overview and public announcements for PortusSophia™"
theme: minima

markdown: kramdown
github:
  is_project_page: false

exclude:
  - archive
  - README.md
  - LICENSE.md
  - Gemfile
  - Gemfile.lock
